# Generated by Django 4.0.3 on 2022-04-04 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0005_rename_user_manga_author_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='rating',
        ),
        migrations.AddField(
            model_name='manga',
            name='rating',
            field=models.ManyToManyField(related_name='mangarating', to='mangas.rating'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='manga',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mangaratings', to='mangas.manga'),
        ),
    ]
