# Generated by Django 4.0.3 on 2022-04-04 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0007_image_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='chapter',
            field=models.ManyToManyField(related_name='manychapter', to='mangas.chapter'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='image',
            field=models.ManyToManyField(to='mangas.image'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='manga',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chaptermanga', to='mangas.manga'),
        ),
    ]
