# Generated by Django 4.0.3 on 2022-04-04 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0009_chapter_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='chapter',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='manga',
            name='rating',
            field=models.ManyToManyField(blank=True, related_name='mangarating', to='mangas.rating'),
        ),
    ]
