# Generated by Django 4.0.3 on 2022-04-08 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0011_rename_image_chapter_images_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manga',
            old_name='chapter',
            new_name='chapters',
        ),
    ]
