# Generated by Django 4.0.3 on 2022-04-11 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0013_alter_manga_chapters'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
