# Generated by Django 4.0.3 on 2022-04-12 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0014_chapter_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='manga',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mangas.manga'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='chapters',
            field=models.ManyToManyField(blank=True, related_name='mangas', to='mangas.chapter'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='ratings',
            field=models.ManyToManyField(blank=True, related_name='mangas', to='mangas.rating'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='manga',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mangas.manga'),
        ),
    ]
