# Generated by Django 4.0.3 on 2022-04-12 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0015_alter_chapter_manga_alter_manga_chapters_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['date']},
        ),
    ]
