# Generated by Django 4.0.3 on 2022-04-12 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0016_alter_chapter_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={},
        ),
    ]
