# Generated by Django 4.0.3 on 2022-04-12 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0017_alter_chapter_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='manga',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagemanga', to='mangas.manga'),
        ),
    ]
