# Generated by Django 4.0.3 on 2022-04-13 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0018_image_manga'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterField(
            model_name='chapter',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='images',
            field=models.ManyToManyField(blank=True, to='mangas.image'),
        ),
    ]
