# Generated by Django 4.0.3 on 2022-04-13 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0019_alter_chapter_options_alter_chapter_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='manga',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapters1', to='mangas.manga'),
        ),
    ]
