# Generated by Django 4.0.3 on 2022-04-14 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0020_alter_chapter_manga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='manga',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mangas.manga'),
        ),
    ]
