# Generated by Django 4.0.3 on 2022-04-14 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0021_alter_chapter_manga'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manga',
            old_name='image',
            new_name='cover',
        ),
    ]
