# Generated by Django 4.0.3 on 2022-04-15 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0023_alter_image_manga'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='coins',
        ),
        migrations.AddField(
            model_name='image',
            name='chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mangas.chapter'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='chapters', to='mangas.image'),
        ),
    ]
