# Generated by Django 4.0.6 on 2023-05-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0025_basicrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='basicRating',
            field=models.ManyToManyField(blank=True, related_name='mangas', to='mangas.basicrating'),
        ),
    ]
